### ISSUE TITLE
Add data import tool

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/pycaboose#5]
I think it would be a good idea to be able to import data into project externally. As in, there should be an external utility that sets a PyCaboose value to something and stores it within the script, without actually running the script.

**Comment by the-lightstack** [comment]
Is this supposed to be a command line utility?
I will try to handle this problem
Regards, Lars

**Comment by JohnathonNow** [comment]
Yes, a command line utility would be good.
Thanks.

**Comment by bottleInALightning** [comment]
So is it supposed to be in the main package or an external file?
If it was in the main package, it would require some kind of trigger (like sys.argv[1], I cant think of something else more elegant right now)

**Comment by JohnathonNow** [comment]
An external script I think makes sense, and after it works I can add it as
a bin to the pypi package.

**Comment by the-lightstack** [comment]
Btw, how is it supposed to insert variables, maybe I get something wrong, but It think it would have to prompt you for a line and the name of the variable (and maybe also its data, or just default none), (or like importing it from a csv file)

I mean, would it have to also insert like "var_name=Value(data)" ?(so it isn't just a random line that is being inserted)

**Comment by JohnathonNow** [comment]
I think prompting the user for a line is fair. I don't think it should insert variables itself. I think it would be best to have the utility take three command line arguments - the script to load into, the line number of the variable to set, and then the data to load in (perhaps a csv file, a string, or a json file). I've modified [database,py](https://github.com/JohnathonNow/pycaboose/blob/master/pycaboose/database.py) to accept a filename in the constructor, so your script could construct a database object with the filename of the script we're loading to, then call `database.write(line number, data)`.

Unfortunately importing pycaboose will alter the script that's meant to alter things, but that shouldn't be an issue.

**Comment by JohnathonNow** [comment]
Resolved by #7.
