### ISSUE TITLE
Duplicated Flag

### ISSUE THREAD

**Issue by the-lightstack** [JohnathonNow/pycaboose#6]
When the user of the script doesn't end his script with a newline, 
It will look like this:
```
a=Value(1)# pycagoose #
#encrypted stuff..
```
and when booting the script up again, it wont recognize the flag and just add a new line.
**Solution**
Adding a newline before appending the flag to the script

**Comment by bottleInALightning** [comment]
How it then looks like:
`
a.value =0# pycaboose #
# gASVBwAAAAAAAABLA0sBhpQu
# pycaboose #
# gASVBwAAAAAAAABLA0sAhpQu
`

**Comment by the-lightstack** [comment]
how it then looks like:
```
a.value =0# pycaboose #
# gASVBwAAAAAAAABLA0sBhpQu
# pycaboose #
# gASVBwAAAAAAAABLA0sAhpQu

```

**Comment by JohnathonNow** [comment]
Good catch, thanks.
