### ISSUE TITLE
Import tool breaks 3.5 compatibility

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/pycaboose#8]
https://github.com/JohnathonNow/pycaboose/blob/84e15e7ba511fa97ef3e438c1eb378294d422f23/bin/manipulate_values.py#L41
The import tool uses fstrings, which weren't in 3.5, so the build now fails.

**Comment by the-lightstack** [comment]
Ok I will fix it, is print("hi {}".format(hi_var)) working in 3.5?

**Comment by JohnathonNow** [comment]
Yes that should work.

**Comment by JohnathonNow** [comment]
Yep, #9 fixed this.
